language: python
python:
  - 2.6
  - 2.7
#  - 3.2
#  - 3.3
install:
  - pip install -e .
  - pip install -r tests/requirements.txt
  - pip install https://github.com/django/django/archive/${DJANGO}.zip#egg=django
  - pip install python-coveralls
script: ./ci.sh
env:
  - DJANGO=1.4.10
  - DJANGO=1.5.5
  - DJANGO=stable/1.6.x
# matrix:
#  exclude:
#    - python: 3.2
#      env: DJANGO=1.4.10
#    - python: 3.3
#      env: DJANGO=1.4.10
after_script:
  - coveralls
