language: python

python:
  - "2.6"
  - "2.7"
  # - "3.2"  # @@@ Does not seem to be supported by Markdown/Pygments
  - "3.3"
  - "3.4"

env:
  - DJANGO=master
  - DJANGO=1.6
  - DJANGO=1.7

install:
  - pip install tox coveralls

script:
  - tox -e py${TRAVIS_PYTHON_VERSION//[.]/}-$DJANGO

matrix:
  exclude:
    - python: "2.6"
      env: DJANGO=1.7
    - python: "2.6"
      env: DJANGO=master
    - python: "3.4"
      env: DJANGO=1.6

after_success: coveralls

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/07df398ea594d3682132
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
