language: python

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"

env:
  - DJANGO=https://github.com/django/django/tarball/master
  - DJANGO=Django<1.6
  - DJANGO=Django<1.7

install:
  - pip install tox coveralls

script:
  - tox -e py${TRAVIS_PYTHON_VERSION//[.]/}-$DJANGO

matrix:
  exclude:
    - python: "2.6"
      env: DJANGO=1.7
    - python: "2.6"
      env: DJANGO=master
    - python: "3.4"
      env: DJANGO=1.6

after_success: coveralls
